-- local ok, dashboard = pcall(require, "dashboard")
-- if not ok then
-- 	return
-- end
--
-- local ok_ascii, ascii = pcall(require, "ascii")
-- local header = ok_ascii and ascii.art.text.neovim.sharp or { "Neovim" }
--
-- dashboard.setup({
-- 	theme = "doom",
-- 	config = {
-- 		header = header, --your header
-- 		center = {
-- 			{
-- 				icon = " ",
-- 				icon_hl = "Title",
-- 				desc = "Find File           ",
-- 				desc_hl = "String",
-- 				key = "b",
-- 				keymap = "SPC f f",
-- 				key_hl = "Number",
-- 				key_format = " %s", -- remove default surrounding `[]`
-- 				action = "lua print(2)",
-- 			},
-- 			{
-- 				icon = " ",
-- 				desc = "Find Dotfiles",
-- 				key = "f",
-- 				keymap = "SPC f d",
-- 				key_format = " %s", -- remove default surrounding `[]`
-- 				action = "lua print(3)",
-- 			},
-- 		},
-- 		footer = {},
-- 	},
-- })
--
-- vim.api.nvim_create_autocmd("VimEnter", {
-- 	once = true,
-- 	callback = function()
-- 		if vim.fn.argc() == 0 then
-- 			vim.cmd("Dashboard")
-- 		end
-- 	end,
-- })
