require("jokerhut.ui.lualine")
require("jokerhut.ui.neo-tree")
require("jokerhut.ui.toggleterm")
require("jokerhut.ui.term-compiler")
require("jokerhut.ui.alpha")
require("jokerhut.ui.markdown")
require("jokerhut.ui.edgy")
